action: pytest, msg: envreport
cwd: /repos/epics-containers.github.io
cmd: /venv/bin/python -m pip freeze
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.10/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/venv/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 68, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/venv/lib/python3.10/site-packages/pip/_internal/commands/__init__.py", line 109, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/venv/lib/python3.10/site-packages/pip/_internal/commands/freeze.py", line 8, in <module>
    from pip._internal.operations.freeze import freeze
  File "/venv/lib/python3.10/site-packages/pip/_internal/operations/freeze.py", line 11, in <module>
    from pip._internal.req.constructors import (
  File "/venv/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 7, in <module>
    from .req_file import parse_requirements
  File "/venv/lib/python3.10/site-packages/pip/_internal/req/req_file.py", line 26, in <module>
  File "/venv/lib/python3.10/site-packages/pip/_internal/network/session.py", line 31, in <module>
    from pip._internal.network.auth import MultiDomainBasicAuth
  File "/venv/lib/python3.10/site-packages/pip/_internal/network/auth.py", line 22, in <module>
    from pip._internal.vcs.versioncontrol import AuthInfo
  File "/venv/lib/python3.10/site-packages/pip/_internal/vcs/__init__.py", line 5, in <module>
    import pip._internal.vcs.bazaar
  File "/venv/lib/python3.10/site-packages/pip/_internal/vcs/bazaar.py", line 7, in <module>
    from pip._internal.vcs.versioncontrol import (
  File "/venv/lib/python3.10/site-packages/pip/_internal/vcs/versioncontrol.py", line 274, in <module>
    class VersionControl:
  File "/venv/lib/python3.10/site-packages/pip/_internal/vcs/versioncontrol.py", line 398, in VersionControl
    def get_url_rev_and_auth(cls, url: str) -> Tuple[str, Optional[str], AuthInfo]:
  File "/usr/lib/python3.10/typing.py", line 309, in inner
    return cached(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 1234, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.10/typing.py", line 1234, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.10/typing.py", line 168, in _type_check
    if arg in (Any, NoReturn, Final, TypeAlias):
  File "/usr/lib/python3.10/typing.py", line 1243, in __eq__
    if not isinstance(other, (_UnionGenericAlias, types.UnionType)):
KeyboardInterrupt
